var subject = require('./mystery.js')
var mock = require('mock-fs');
subject.inc(-100,"r46HujW-7nt");
subject.weird(88,70,41,"stricterDiff");
subject.fileTest('pathContent/file1','path/fileExists');
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
subject.inc(-101,"fmpmdWmeon-");
subject.weird(88,70,41,"stricterDiff");
subject.fileTest('pathContent/file1','path/fileExists');
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
subject.inc(-100,77);
subject.weird(88,70,41,"stricterDiff");
subject.fileTest('pathContent/file1','path/fileExists');
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
subject.inc(-101,77);
subject.weird(88,70,41,"stricterDiff");
subject.fileTest('pathContent/file1','path/fileExists');
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
