var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(0,"GG768uB6BeY");
subject.weird(8,0,41,"strictDiff");
subject.fileTest('path/fileExists','pathContent/file1');
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
subject.inc(-1,"tkBvKtcl0BU");
subject.weird(8,0,41,"strictDiff");
subject.fileTest('path/fileExists','pathContent/file1');
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
subject.inc(0,undefined);
subject.weird(8,0,41,"strictDiff");
subject.fileTest('path/fileExists','pathContent/file1');
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
subject.inc(-1,undefined);
subject.weird(8,0,41,"strictDiff");
subject.fileTest('path/fileExists','pathContent/file1');
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
